name: Patch Scaffolds

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  scaffold-matrix:
    if: github.event.pull_request.merged == true && (startsWith( github.head_ref, 'athos-patch-generate-' ) || startsWith( github.head_ref, 'searchspring-patch-generate-' ))
    runs-on: ubuntu-latest
    steps:
      - id: scaffolds
        run: |
          source=`echo '${{ github.head_ref }}' | jq -Rr 'split("-")[0]'`;
          framework=`echo '${{ github.head_ref }}' | jq -Rr 'split("-")[3]'`;

          if [ "$source" == "athos" ]; then
            owner="athoscommerce"
          elif [ "$source" == "searchspring" ]; then
            owner="searchspring"
          else
            echo "Unknown source: $source"
            exit 1
          fi

          scaffolds=$(gh search repos --owner "$owner" "snapfu-scaffold-$framework" --json name --jq '[.[].name]')
          echo "source=$source" >> $GITHUB_OUTPUT
          echo "owner=$owner" >> $GITHUB_OUTPUT
          echo "scaffolds=$scaffolds" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.MACHINE_ACTION_WORKFLOW_PAT }}
    outputs:
      source: ${{ steps.scaffolds.outputs.source }}
      owner: ${{ steps.scaffolds.outputs.owner }}
      scaffolds: ${{ steps.scaffolds.outputs.scaffolds }}
  patch-scaffold:
    if: github.event.pull_request.merged == true && (startsWith( github.head_ref, 'athos-patch-generate-' ) || startsWith( github.head_ref, 'searchspring-patch-generate-' )) && needs.scaffold-matrix.outputs.scaffolds != '[]'
    runs-on: ubuntu-latest
    needs:
      - scaffold-matrix
    strategy:
      matrix:
        scaffold: ${{ fromJSON(needs.scaffold-matrix.outputs.scaffolds) }}
    steps:
      - name: Extract Variables
        id: variables
        run: |
          source=`echo '${{ github.head_ref }}' | jq -Rr 'split("-")[0]'`;
          echo "source=$source" >> $GITHUB_OUTPUT
          echo "Using source: $source";

          framework=`echo '${{ github.head_ref }}' | jq -Rr 'split("-")[3]'`;
          echo "framework=$framework" >> $GITHUB_OUTPUT
          echo "Using framework: $framework";

          version=`echo '${{ github.head_ref }}' | jq -Rr 'split("-")[4]'`;
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Using version: $version";

      - name: Validate Variables
        run: |
          if [ "${{ steps.variables.outputs.source }}" == "" ]; then 
            echo "Could not determine source";
            exit 1;
          fi;
          if [ "${{ steps.variables.outputs.framework }}" == "" ]; then 
            echo "Could not determine framework";
            exit 1;
          fi;
          if [ "${{ steps.variables.outputs.version }}" == "" ]; then 
            echo "Could not determine version";
            exit 1;
          fi;

      - name: Setup Node
        id: setup-node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Snapfu
        run: |
          npm install -g snapfu

      - name: Checkout Scaffold
        uses: actions/checkout@v6
        with:
          repository: "${{ needs.scaffold-matrix.outputs.owner }}/${{ matrix.scaffold }}"
          path: "${{ matrix.scaffold }}"
          ref: "production"
          token: ${{ secrets.MACHINE_ACTION_WORKFLOW_PAT }}

      - name: Patch Scaffold
        working-directory: ${{ matrix.scaffold }}
        run: |
          git config --global user.name "athos-machine"
          git config --global user.email "machine@athoscommerce.com"
          git checkout -b patch-${{ matrix.scaffold }}-${{ steps.variables.outputs.version }}
          snapfu patch fetch
          snapfu patch apply ${{ steps.variables.outputs.version }} --ci
          git add .
          git commit -m "auto generated scaffolding patch from 'Patch Scaffold' action workflow"
          git push -u origin patch-${{ matrix.scaffold }}-${{ steps.variables.outputs.version }}
 
      - name: Create PR
        run: |
          gh pr create \
            --title "Patch Scaffold ${{ matrix.scaffold }} to ${{ steps.variables.outputs.version }}" \
            --body "" \
            --repo "https://github.com/${{ needs.scaffold-matrix.outputs.owner }}/${{ matrix.scaffold }}" \
            --base "production" \
            --head "patch-${{ matrix.scaffold }}-${{ steps.variables.outputs.version }}" \
            --project "Snap" \
            --reviewer "${{ needs.scaffold-matrix.outputs.owner }}/snap-team"
        env:
          GITHUB_TOKEN: ${{ secrets.MACHINE_ACTION_WORKFLOW_PAT }}